//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlythuvien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int reader_id { get; set; }
        public int book_id { get; set; }
        public System.DateTime borrow_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
